name: CI

on:
  push:
    branches: [main]
    paths-ignore: ["**/*.md", "LICENSE", ".gitignore"]
  pull_request:
    branches: [main]
    paths-ignore: ["**/*.md", "LICENSE", ".gitignore"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: cplieger/ci/.github/workflows/ts-ci.yaml@17b699a97542f07b55e6b576456044731954c6fd # v1
    with:
      working-directory: "."
